sudo: required
language: generic 
services:
    - docker

before_install:
    - docker build -t axebite/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true axebite/docker-react npm run test    

