version: '3'
services:
    web:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "8080:3000"
        volumes: 
            - /app/node_modules
            - .:/app
        stdin_open: true 
        environment:
            - CHOKIDAR_USEPOLLING=true
    tests:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules
            - .:/app
        stdin_open: true 
        environment:
            - CHOKIDAR_USEPOLLING=true
        command: ["npm", "run", "test"]



#docker-compose down && docker-compose up --build        
#For windows hot reloading
# enviroment:
    # - CHOKIDAR_USEPOLLING=true